version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: PEPS
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8888:80
    depends_on:
      - mariadb
  apache:
    build: ./apache
    container_name: apache
    volumes:
      - ./miweb:/usr/local/apache2/htdocs/
    ports:
      - 7777:80
    restart: unless-stopped
    depends_on:
      - python
      - mariadb
  python:
    build: ./python
    container_name: python
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - mariadb
